image: maven:3.5.4-jdk-8

services:
    - postgres:12.2-alpine

variables:
    DATABASE_URL_TEST: postgres://gael:@postgres:5432/qieam
    POSTGRES_DB: qieam
    POSTGRES_USER: gael
    POSTGRES_HOST_AUTH_METHOD: trust

stages:
    - build
    - test
    - analyze

build_job:
    stage: build
    script:
        - mvn compile

unit_test:
    stage: test
    script:
        - mvn clean test
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
    artifacts:
        when: always
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
                - target/failsafe-reports/TEST-*.xml

sonar_analyze:
    stage: analyze
    image: maven:3.6.3-jdk-11
    script:
        - mvn verify sonar:sonar -Dsonar.projectKey=epsi-i1-dev_tp_ci_loic_brison -Dsonar.qualitygate.wait=true
